[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "upgrade-insecure-requests; block-all-mixed-content; default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https:; img-src 'self' data: https:; connect-src 'self' https:; frame-src https:; object-src 'none'; media-src https:; worker-src 'self' https:; child-src https:; form-action 'self' https:; base-uri 'self'"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
Referrer-Policy = "no-referrer-when-downgrade"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"

[[redirects]]
from = "http://credion.com.au/*"
to = "https://credion.com.au/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.credion.com.au/*"
to = "https://credion.com.au/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npm run build"
publish = "dist"